// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyBX_tIiEhOHDxM8HPVEAy2uF2KG_z588',
    appId: '1:781999546984:web:382afe49d3762bd9b2d1dd',
    messagingSenderId: '781999546984',
    projectId: 'blooddonner-df770',
    authDomain: 'blooddonner-df770.firebaseapp.com',
    storageBucket: 'blooddonner-df770.appspot.com',
    measurementId: 'G-8GFSTLMF2Y',
  );

  static FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCeMnbNGn1SH6Orp_ifB9QnYonLNg6RSSI',
    appId: '1:781999546984:android:1e44d0c706e44da3b2d1dd',
    messagingSenderId: '781999546984',
    projectId: 'blooddonner-df770',
    storageBucket: 'blooddonner-df770.appspot.com',
  );

  static FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4psIPcAdxstvWe2mP4mOdsBxT97MqY7A',
    appId: '1:781999546984:ios:458bcd910f248bcab2d1dd',
    messagingSenderId: '781999546984',
    projectId: 'blooddonner-df770',
    storageBucket: 'blooddonner-df770.appspot.com',
    iosBundleId: 'com.example.donnerfirebase',
  );
}
